name: GitHub Pages

on:
  push:
    branches: [master]
  schedule:
    - cron: "30 8 * * *"  # daily at 08:30 UTC
  workflow_dispatch:
  # Allows manual triggering of the workflow
jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: tools/search

      - name: Run generation script
        run: python main.py generate
        working-directory: tools/search

      # - name: Copy generated files
      #   run: |
      #     mkdir -p public/output
      #     cp tools/search/output/* public/output/

      - name: Commit generated output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/output
          git commit -m "Daily output update at 08:30 UTC" || echo "No changes to commit"
          git push

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "21.6.1"
          cache: "pnpm"

      - name: Install Node dependencies
        run: pnpm install

      - name: Build site
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./out
          cname: patrickdesjardins.com
